# Generated by Django 6.0 on 2025-12-25 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('linkedin_url', models.URLField(max_length=500)),
                ('team_id', models.IntegerField(help_text='Team identifier (1 or 2)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['team_id', 'name'],
            },
        ),
    ]
