# Generated by Django 6.0 on 2026-01-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the candidate', null=True),
        ),
    ]
