# Generated by Django 4.2.7 on 2026-01-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_reset_token_user_reset_token_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_token_created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
